# Введение в NumPy.

## 1. Подключение модуля.

In [1]:
import numpy as np
np.random.seed(42)

## 2. Создание массивов.

### 2.1. Из списков Python:

In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([1, 2, 3.14, 4, 5])

array([1.  , 2.  , 3.14, 4.  , 5.  ])

In [4]:
np.array([1, 2, 3, 4, 5], dtype=np.float64)

array([1., 2., 3., 4., 5.])

In [5]:
np.array([1, 2.72, [1, 2, 3], {'a': 1, 'b': 2}])

C:\Users\Michail\AppData\Local\Temp\ipykernel_14396\1202983094.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([1, 2.72, [1, 2, 3], {'a': 1, 'b': 2}])


array([1, 2.72, list([1, 2, 3]), {'a': 1, 'b': 2}], dtype=object)

In [6]:
np.array([[i + j for i in range(5)] for j in range(5)])

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

Обратите внимание, что массив numpy содержит данные одного типа. При попытке создания массива из разнородных данных NumPy будет производить повышающее приведение типов до тех пор, пока все данные не будут унифицированы. 

Так во стором примере, из-за наличия в данных числа 3.14, итоговый тип данных массива - float. В третьем примере итоговый тип - object. Тип object наиболее общий и означает, что массив состоит из объектов языка Python (в нашем примере int, float, list и dict).

При необходимости можно явно указать желаемый тип данных, путем присвоение атрибуту `dtype` допустимого значения. 

Также обратите внимание на последний пример. В NumPy возможно создание многомерных массивов из списков со вложенными списками. Так в нашем примере вложенные списки интерпретируются, как строки двухмерной матрицы. 

### 2.2. С нуля:

**zeros:**

С помощью функции zeros() можно создать массив, заполненный нулями. 

In [7]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.zeros((3, 3, 3), dtype=np.float32)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

**ones:**

Угадайте, что можно сделать с помощтю функции ones?

In [9]:
np.ones(10, dtype=np.uint8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint8)

**full:**

Иногда необходимо создать новый массив, проинициализированный определёнными значениями отличными от нуля и единицы. Например, при работе с изображениями, может потребоваться необходимости создать пустое белое изображение, где значение белого задается числом 255. Специально для таких целей существует функция full():

In [10]:
np.full(shape=(5, 5), fill_value=255, dtype=np.uint8)

array([[255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255]], dtype=uint8)

**arange:**

Часто необходимо заполнить новый массив арифметической прогрессией. Для этой цели существует функция arange:

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(start=5, stop=11)

array([ 5,  6,  7,  8,  9, 10])

In [13]:
np.arange(start=-10, stop=11, step=2)

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,  10])

**linspace:**

Не всегда удобно вычислять шаг между соседними точками. Например, мы хотим взять 378 точек из отрезка $[0, 2\pi]$. Чтобы не тратить время на вычисления шага в NumPy есть функция linspace, котороя берет заданное число точек из заданного диапазона, включая границы.

In [14]:
np.linspace(0, np.pi, 32)

array([0.        , 0.1013417 , 0.2026834 , 0.3040251 , 0.40536679,
       0.50670849, 0.60805019, 0.70939189, 0.81073359, 0.91207529,
       1.01341699, 1.11475868, 1.21610038, 1.31744208, 1.41878378,
       1.52012548, 1.62146718, 1.72280887, 1.82415057, 1.92549227,
       2.02683397, 2.12817567, 2.22951737, 2.33085907, 2.43220076,
       2.53354246, 2.63488416, 2.73622586, 2.83756756, 2.93890926,
       3.04025096, 3.14159265])

**random:**

Часто полезно заполнить только что созданную матрицу случайными числами из заданного закона распределения. Например, в Глубоком обучение существует ряд статей, доказывающих, что при определенных условиях, эффективно инициализировать веса модели случайными значениями из нормального закона распределения. Для подобных целей в NumPy есть модуль random.

In [15]:
np.random.normal(loc=0, scale=1, size=(3, 3))

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439]])

In [16]:
np.random.uniform(low=-10, high=10, size=(3, 3))

array([[-6.36350066, -6.3319098 , -3.91515514],
       [ 0.49512863, -1.36109963, -4.1754172 ],
       [ 2.23705789, -7.21012279, -4.15710703]])

In [17]:
np.random.randint(0, 10, size=(3, 3))

array([[2, 6, 3],
       [8, 2, 4],
       [2, 6, 4]])

**eye:**

Создание единичной матрицы:**

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.eye(5, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

**empty:**

Вы также можете создать "пустой" массив. Значения в его ячейках - мусор, оставшийся в этих ячейках от предыдущих вычислений. В ходе выполнения программы эти ячейки могут быть перезаписаны по вашему усмотрению.

In [20]:
np.empty(5)

array([1., 1., 1., 1., 1.])

## 3. Атрибуты массивов.

In [21]:
def print_attributes(arr: np.ndarray) -> None:
    
    print('\n--------------------------------------------------')
    print(f'\n{array}\n')
    print(f'Array shape: {arr.shape};')
    print(f'Array dimension: {arr.ndim};')
    print(f"Array element's amount: {arr.size};")
    print(f"Array element's size: {arr.itemsize}")
    print(f'Array memory space: {arr.nbytes};')
    print('--------------------------------------------------')

In [22]:
arrays = [np.random.uniform(0, 10, size=3),
          np.random.uniform(0, 10, size=(3, 3)),
          np.random.uniform(0, 10, size=(3, 3, 3))]

for array in arrays:
    print_attributes(array)


--------------------------------------------------

[4.50499252 0.13264961 9.42201756]

Array shape: (3,);
Array dimension: 1;
Array element's amount: 3;
Array element's size: 8
Array memory space: 24;
--------------------------------------------------

--------------------------------------------------

[[5.63288218 3.85416503 0.15966252]
 [2.30893826 2.41025466 6.83263519]
 [6.09996658 8.33194912 1.73364654]]

Array shape: (3, 3);
Array dimension: 2;
Array element's amount: 9;
Array element's size: 8
Array memory space: 72;
--------------------------------------------------

--------------------------------------------------

[[[3.91060608 1.82236088 7.5536141 ]
  [4.25155874 2.07941663 5.67700328]
  [0.31313292 8.42284775 4.49754133]]

 [[3.95150236 9.26658866 7.27271996]
  [3.26540769 5.70443974 5.2083426 ]
  [9.61172024 8.44533849 7.4732011 ]]

 [[5.39692132 5.86751166 9.65255307]
  [6.07034248 2.75999182 2.96273506]
  [1.65266939 0.15636407 4.23401481]]]

Array shape: (3, 3, 3);

## 4. Доступ к элементам массива.

In [23]:
arr_1d, arr_2d, arr_3d = arrays

Массивы NumPy индексируются аналогично списком языка Python:

In [24]:
arr_1d[0]

4.5049925196954295

In [25]:
arr_2d[-1]

array([6.09996658, 8.33194912, 1.73364654])

### 4.1. Индексация многомерных массивов.

Многомерные массивы поддерживают следующий вид индексации:

In [26]:
arr_2d[0, 2]

0.15966252220214194

In [27]:
arr_3d[0, 1, 2]

5.677003278199915

Эти записи аналогичны следующим записям:

In [28]:
arr_2d[0][2]

0.15966252220214194

In [29]:
arr_3d[0][1][2]

5.677003278199915

### 4.2. Срезы.

Массивы в NumPy также поддерживают операцию получения среза.

**Одномерный случай:** 

In [30]:
numbers = np.arange(20)
numbers

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
numbers[5: 10]

array([5, 6, 7, 8, 9])

In [32]:
numbers[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
numbers[1::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [34]:
numbers[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

**Многомерный случай:**

In [35]:
arr_2d

array([[5.63288218, 3.85416503, 0.15966252],
       [2.30893826, 2.41025466, 6.83263519],
       [6.09996658, 8.33194912, 1.73364654]])

In [36]:
arr_2d[1:, 1:] = 100

In [37]:
arr_2d

array([[  5.63288218,   3.85416503,   0.15966252],
       [  2.30893826, 100.        , 100.        ],
       [  6.09996658, 100.        , 100.        ]])

In [38]:
arr_2d[::2, ::2]

array([[  5.63288218,   0.15966252],
       [  6.09996658, 100.        ]])

In [39]:
arr_2d[::-1, 0]

array([6.09996658, 2.30893826, 5.63288218])

Важное замечание: в ходе получения среза, мы не создаем новый массив, а лишь получаем доступ к фрагменту существующего массива, иначе говоря, получаем его представление(view). Поэтому стоит быть аккуратными:

In [40]:
numbers

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
my_slice = numbers[5: 10]
my_slice[:] = 100
numbers

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

При необходимости скопировать массив, используйте явно метод copy().

### 4.3. Индексация массивом.

Можно получить сразу несколько элементов, индексируя массив последовательностью индексов.

**Одномерный случай:**

In [42]:
data = np.random.randint(0, 10, size=15)
data

array([0, 7, 7, 2, 0, 7, 2, 2, 0, 4, 9, 6, 9, 8, 6])

In [43]:
indices = [2, 7, 8, 13]
data[indices]

array([7, 2, 0, 8])

**Многомерный случай:**

In [44]:
data_2d = data.reshape(5, 3)
data_2d

array([[0, 7, 7],
       [2, 0, 7],
       [2, 2, 0],
       [4, 9, 6],
       [9, 8, 6]])

In [45]:
indices1 = np.array([1, 2, 4])
indices2 = np.array([0, 2])

ind1 = np.tile(indices1, indices2.size)
ind2 = np.repeat(indices2, indices1.size)

data_2d[ind1, ind2].reshape(indices2.size, -1).T

array([[2, 7],
       [2, 0],
       [9, 6]])

In [46]:
data_2d[indices1][:, indices2]

array([[2, 7],
       [2, 0],
       [9, 6]])

## 5. Изменение формы массива.

**reshape:**

Чаще всего для изменения формы массива используется метод reshape, которая возвращает новый массив с измененной формой.

In [47]:
numbers

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [48]:
numbers.reshape(5, 4)

array([[  0,   1,   2,   3],
       [  4, 100, 100, 100],
       [100, 100,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19]])

**T:**

Часто нам не требуется изобратеть новую форму массива, а необходимо лишь транспонировать его. Для этого достаточно вызвать отрибут T, возвращающий странспонированную матрицу (работает только с многомерными массивами).

In [49]:
arr_2d

array([[  5.63288218,   3.85416503,   0.15966252],
       [  2.30893826, 100.        , 100.        ],
       [  6.09996658, 100.        , 100.        ]])

In [50]:
arr_2d.T

array([[  5.63288218,   2.30893826,   6.09996658],
       [  3.85416503, 100.        , 100.        ],
       [  0.15966252, 100.        , 100.        ]])

**newaxis:**

Также для векторизации многих операций вам может понадобиться создать новое измерение в массиве. Для этот следует использовать np.newaxis:

In [51]:
numbers[np.newaxis, :]

array([[  0,   1,   2,   3,   4, 100, 100, 100, 100, 100,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19]])

In [52]:
numbers[:, np.newaxis]

array([[  0],
       [  1],
       [  2],
       [  3],
       [  4],
       [100],
       [100],
       [100],
       [100],
       [100],
       [ 10],
       [ 11],
       [ 12],
       [ 13],
       [ 14],
       [ 15],
       [ 16],
       [ 17],
       [ 18],
       [ 19]])

## 6. Объединение и разбиение массивов.

### 6.1 Объединение.

In [54]:
arr1 = np.arange(3)
arr2 = np.arange(3, 6)

matrix = np.random.randint(0, 6, size=(3, 3))

print(arr1, arr2, matrix, sep='\n\n')

[0 1 2]

[3 4 5]

[[2 2 0]
 [2 4 5]
 [2 0 4]]


**concatenate:**

Дописывает один массив в конец другого. Массивы должны иметь одинаковое число измерений. С помощью параметра axis возможен выбор измерения, по которому массивы будут конкатенироваться.

In [53]:
np.concatenate((arr1, arr2))

array([0, 1, 2, 3, 4, 5])

In [55]:
np.concatenate((matrix, arr1[np.newaxis, :]))

array([[2, 2, 0],
       [2, 4, 5],
       [2, 0, 4],
       [0, 1, 2]])

In [56]:
np.concatenate((matrix, arr1[:, np.newaxis]), axis=1)

array([[2, 2, 0, 0],
       [2, 4, 5, 1],
       [2, 0, 4, 2]])

**hstack:**

В случае двумерного массива приписывает новый столбец.

In [57]:
np.hstack((matrix, arr1[:, np.newaxis]))

array([[2, 2, 0, 0],
       [2, 4, 5, 1],
       [2, 0, 4, 2]])

**vstack:**

В случае двумерного массива приписывает новую строку.

In [58]:
np.vstack((matrix, arr1))

array([[2, 2, 0],
       [2, 4, 5],
       [2, 0, 4],
       [0, 1, 2]])

### 6.2. Разбиение.

In [59]:
arr = np.arange(20).reshape(4, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

**split:**

Вы можете разделить массив с помощью функции split, передав ей в качестве аргументов массив для разделения и индексы, по которым следует разделять массив.

In [61]:
np.split(arr, (1, 3), axis=1)

[array([[ 0],
        [ 5],
        [10],
        [15]]),
 array([[ 1,  2],
        [ 6,  7],
        [11, 12],
        [16, 17]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19]])]

## 7. Агрегирование.

Функция агрегирования могут быть очень полезными при разведочном анализе данных.

In [63]:
data = np.random.normal(loc=0, scale=1, size=(2000, 500))

### 7.1. Вычисление суммы.

В Python есть встроенная функция для вычисления суммы элементов итерируемого объекта, одна она имеет ряд недостатков. Во-первых, вы будете сильно удивлены результатом применениия данной функции к многомерному массиву numpy, поскольку суммирование осуществляется только вдоль первой оси. Во-вторых, из-за реализации Python, функция sum выполняется гораздо медленнее в сравнении с np.sum. 

In [68]:
%timeit data.reshape(-1)

488 ns ± 6.66 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [67]:
%timeit sum(reshaped)

179 ms ± 2.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [65]:
%timeit np.sum(data)

1.63 ms ± 18.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Также с помощью функции np.sum() возможно вычисление сумм элементов каждой строки или каждого столбца:

In [71]:
print(np.sum(data, axis=0).shape)

<class 'tuple'>


In [70]:
print(np.sum(data, axis=1).shape)

(2000,)


### 7.2. Вычисление произведения.

Помимо суммы возможно вычисление произведения всех элементов массива, или вычисление произведения элементов вдоль требуемого измерения.

In [72]:
np.prod(data)

-0.0

### 7.3. Вычисление стреднего значения.

In [73]:
data.mean()

0.00045438494778208123

In [74]:
print(data.mean(axis=0).shape)

(500,)


### 7.4. Среднеквадратичное отклонение.

In [75]:
data.std()

0.9996403458453681

### 7.5. Максимум и минимум.

In [76]:
data.max()

4.57891438757606

In [77]:
data.min()

-4.899799361837897

### 7.6. Положения максимального и минимального элементов.

Иногда полезно знать положение максимального или минимального элемента в нашем массиве. Для этого в NumPy существуют специальные функции:

In [71]:
np.unravel_index(np.argmax(data), shape=data.shape)

(1166, 352)

In [72]:
np.unravel_index(np.argmin(data), shape=data.shape)

(902, 147)

### 7.7. Сортировки.

Некоторые задачи требуют осуществление сортировки. В NumPy существуют несколько видов сортировок.

In [78]:
data = np.random.normal(loc=5, scale=1, size=(5, 4))
data

array([[5.26827428, 6.67230231, 6.62700722, 5.74034543],
       [4.96538225, 6.89930451, 4.77697984, 5.49593012],
       [7.76363829, 5.38501865, 4.63419395, 3.61344152],
       [4.36587695, 5.23885243, 6.33878419, 5.74451331],
       [5.74335626, 4.21153865, 4.24494212, 5.05588282]])

**sort:**

Функция sort() осуществляет непосредственную сортировку массива.

In [79]:
np.sort(data)

array([[5.26827428, 5.74034543, 6.62700722, 6.67230231],
       [4.77697984, 4.96538225, 5.49593012, 6.89930451],
       [3.61344152, 4.63419395, 5.38501865, 7.76363829],
       [4.36587695, 5.23885243, 5.74451331, 6.33878419],
       [4.21153865, 4.24494212, 5.05588282, 5.74335626]])

В случае многомерного массива sort сортрует данные в рамках строки. Однако с помощью параметра axis возможна сортировка по столбцам:

In [80]:
np.sort(data, axis=0)

array([[4.36587695, 4.21153865, 4.24494212, 3.61344152],
       [4.96538225, 5.23885243, 4.63419395, 5.05588282],
       [5.26827428, 5.38501865, 4.77697984, 5.49593012],
       [5.74335626, 6.67230231, 6.33878419, 5.74034543],
       [7.76363829, 6.89930451, 6.62700722, 5.74451331]])

**argsort:**

Еще один способ сортировки массива - функция argsort, которая возвращает не отсортированный массив, а последовательность индексов - положения элементов в отсортированной последовательности. 

In [81]:
np.argsort(data)

array([[0, 3, 2, 1],
       [2, 0, 3, 1],
       [3, 2, 1, 0],
       [0, 1, 3, 2],
       [1, 2, 3, 0]], dtype=int64)

In [82]:
np.argsort(data, axis=0)

array([[3, 4, 4, 2],
       [1, 3, 2, 4],
       [0, 2, 1, 1],
       [4, 0, 3, 0],
       [2, 1, 0, 3]], dtype=int64)

### 7.8. Nan-безопасное агрегирование.

Иногда данные, с которыми мы работаем, могут быть неполными. В NumPy пропущенные данные принято обозначать специальным значением - np.nan, сигнализирующим об отсутствии данных. Nan имеет очень интересную механику взаимодействия с остальными типами. При проведении любых операций между nan-ом и экземпляром любого другого типа данных результат вычисления - nan.

In [83]:
arr = np.array([0, 1, 2, np.nan, 3])
arr

array([ 0.,  1.,  2., nan,  3.])

In [84]:
np.sum(arr)

nan

Как мы видим, подобное поведение может сильно портить результаты, и замедлять обработку данных. К счастью, в NumPy существуют nan-безопасные аналоги функций агрегирования. 

In [85]:
np.nansum(arr)

6.0

Nan-безопасные функции относятся к nan-ам, как к нулевым значениям, или просто игнорируют их.

In [86]:
arr = np.array([1, 2, 3, 4, np.nan, 5])
np.nanmin(arr)

1.0

## 8. Операции над массивами и векторизация.

### 8.1. Арифметические операции.

Из-за динамической типизации Python очень плохо справляется с выполнением арифметических операций над большими объемами данных. В частности очень медленно выполняются операции в цикле. 

Например, предположим, что нам нужно посчитать матрицу значений, обратных к данным.

In [87]:
def get_reciprocal(array: np.ndarray) -> np.ndarray:
    
    for i in range(array.shape[0]):
        array[i] = 1. / array[i]
        
    return array

In [88]:
array = np.random.uniform(1, 5, size=10000000)

In [89]:
%timeit get_reciprocal(array)

5.31 s ± 155 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [90]:
%timeit 1 / array

31.4 ms ± 1.78 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Как видите NumPy справляется с этой задачей гораздо быстрее Python.

NumPy поддерживает арифметические операции между массивами одной формы, массивами и числами, а также между массивами разной формы.

Отдельно остановимся на операциях между массивами разной формы. Подобные операции позволяют векторизовать вычисления, т.е. избежать использования циклов for, что значительно ускоряет вычисления. 

Рассмотрим пример, в котором нам необходимо найти разницу между всеми парами чисел в массиве:

In [91]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
array[:, np.newaxis] - array

array([[ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9],
       [ 1,  0, -1, -2, -3, -4, -5, -6, -7, -8],
       [ 2,  1,  0, -1, -2, -3, -4, -5, -6, -7],
       [ 3,  2,  1,  0, -1, -2, -3, -4, -5, -6],
       [ 4,  3,  2,  1,  0, -1, -2, -3, -4, -5],
       [ 5,  4,  3,  2,  1,  0, -1, -2, -3, -4],
       [ 6,  5,  4,  3,  2,  1,  0, -1, -2, -3],
       [ 7,  6,  5,  4,  3,  2,  1,  0, -1, -2],
       [ 8,  7,  6,  5,  4,  3,  2,  1,  0, -1],
       [ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0]])

In [93]:
print(array[:, np.newaxis], array, sep='\n\n')

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

[0 1 2 3 4 5 6 7 8 9]


In [94]:
print(array[:, np.newaxis].shape, array.shape)

(10, 1) (10,)


Проведение операций над массивами разных размеров называется транслированием (broadcasting). Транслированием осуществляется по определенным правилам:

+ Если размерность двух массивов отличается, форма массива с меньшей размерностью дополняется единицей с левой стороны;  
+ Если форма двух массивов не совпадает в каком-то измерении, массив с формой, равной 1 в этом измерении, растягивается вплоть до соответствия форме второго массива;  
+ Если в каком-то измерении размеры массивов различаются и ни один не равен 1, генерируется ошибка;

![broadcasting](broadcasting.png)

### 8.2. Логические операции и маскирование.

Так же над массивами можно выполнять различные логические операции. Логика здесь аналогична логике с арифметическими операциями. Однако, есть одно интересное свойство, полученные булевы массивы можно использовать в качестве масок, т.е. индексировать ими массивы. 

Рассмотрим пример.

In [95]:
array = np.random.randint(0, 10, size=(5, 5))
array

array([[1, 0, 5, 7, 1],
       [2, 8, 1, 2, 8],
       [3, 2, 9, 6, 2],
       [5, 1, 8, 3, 6],
       [4, 4, 0, 4, 7]])

Предположим, наша задача вывесте все элементы этого массива большие пяти. Это очень легко сделать с помощью маски.

In [96]:
mask = array > 5
mask

array([[False, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True,  True, False],
       [False, False,  True, False,  True],
       [False, False, False, False,  True]])

In [97]:
array[mask]

array([7, 8, 8, 9, 6, 8, 6, 7])

Или короче:

In [98]:
array[array > 5]

array([7, 8, 8, 9, 6, 8, 6, 7])

Также возможно составление сложных условий в маске. Например, теперь мы хотим вывести все нечетные элементы, меньшие или равные пяти.

In [99]:
array[(array <= 5) | (array % 2 == 1)]

array([1, 0, 5, 7, 1, 2, 1, 2, 3, 2, 9, 2, 5, 1, 3, 4, 4, 0, 4, 7])

Обратите внимание, что мы использовали побитовое И для составления сложного условия, а не оператор and.

### 8.3. Математические функции.

Также в NumPy есть большое количество реализованных математических функций.

К их числу относятся:

**Экспонента:**

In [95]:
x = np.linspace(0, 10, 10)
x

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [96]:
np.exp(x)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

**Тригонометрические функции:**

In [97]:
x = np.linspace(0, np.pi, 10)
x

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

In [98]:
np.sin(x)

array([0.00000000e+00, 3.42020143e-01, 6.42787610e-01, 8.66025404e-01,
       9.84807753e-01, 9.84807753e-01, 8.66025404e-01, 6.42787610e-01,
       3.42020143e-01, 1.22464680e-16])

In [99]:
np.cos(x)

array([ 1.        ,  0.93969262,  0.76604444,  0.5       ,  0.17364818,
       -0.17364818, -0.5       , -0.76604444, -0.93969262, -1.        ])

In [100]:
np.tan(x)

array([ 0.00000000e+00,  3.63970234e-01,  8.39099631e-01,  1.73205081e+00,
        5.67128182e+00, -5.67128182e+00, -1.73205081e+00, -8.39099631e-01,
       -3.63970234e-01, -1.22464680e-16])

**Обратные тригонометрические функции:**

In [101]:
x = np.linspace(-1, 1, 10)
x

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [102]:
np.arcsin(x)

array([-1.57079633, -0.89112251, -0.58903097, -0.33983691, -0.11134101,
        0.11134101,  0.33983691,  0.58903097,  0.89112251,  1.57079633])

In [103]:
np.arccos(x)

array([3.14159265, 2.46191883, 2.1598273 , 1.91063324, 1.68213734,
       1.45945531, 1.23095942, 0.98176536, 0.67967382, 0.        ])

In [104]:
x = np.linspace(-0.5 * np.pi, 0.5 * np.pi, 10)
x

array([-1.57079633, -1.22173048, -0.87266463, -0.52359878, -0.17453293,
        0.17453293,  0.52359878,  0.87266463,  1.22173048,  1.57079633])

In [105]:
np.arctan(x)

array([-1.00388482, -0.88486958, -0.71750578, -0.48234791, -0.17279243,
        0.17279243,  0.48234791,  0.71750578,  0.88486958,  1.00388482])

**Гиперболические функции:**

In [106]:
x = np.linspace(-2, 2, 10)

In [107]:
np.cosh(x)

array([3.76219569, 2.47439497, 1.68346238, 1.23057558, 1.02479314,
       1.02479314, 1.23057558, 1.68346238, 2.47439497, 3.76219569])

In [108]:
np.sinh(x)

array([-3.62686041, -2.26332289, -1.35426939, -0.71715846, -0.22405573,
        0.22405573,  0.71715846,  1.35426939,  2.26332289,  3.62686041])

In [109]:
np.tanh(x)

array([-0.96402758, -0.9146975 , -0.8044548 , -0.58278295, -0.21863508,
        0.21863508,  0.58278295,  0.8044548 ,  0.9146975 ,  0.96402758])

**Обратные гиперболические функции:**

In [110]:
np.arcsinh(x)

array([-1.44363548, -1.22519002, -0.95780045, -0.62514512, -0.22043272,
        0.22043272,  0.62514512,  0.95780045,  1.22519002,  1.44363548])

In [111]:
np.arccosh(np.abs(x) + 1)

array([1.76274717, 1.59073092, 1.37885567, 1.09861229, 0.6549003 ,
       0.6549003 , 1.09861229, 1.37885567, 1.59073092, 1.76274717])

**Модуль:**

In [112]:
x = np.linspace(-10, 10, 15)
x

array([-10.        ,  -8.57142857,  -7.14285714,  -5.71428571,
        -4.28571429,  -2.85714286,  -1.42857143,   0.        ,
         1.42857143,   2.85714286,   4.28571429,   5.71428571,
         7.14285714,   8.57142857,  10.        ])

In [113]:
np.abs(x)

array([10.        ,  8.57142857,  7.14285714,  5.71428571,  4.28571429,
        2.85714286,  1.42857143,  0.        ,  1.42857143,  2.85714286,
        4.28571429,  5.71428571,  7.14285714,  8.57142857, 10.        ])

**Специальные функции:**

In [114]:
x

array([-10.        ,  -8.57142857,  -7.14285714,  -5.71428571,
        -4.28571429,  -2.85714286,  -1.42857143,   0.        ,
         1.42857143,   2.85714286,   4.28571429,   5.71428571,
         7.14285714,   8.57142857,  10.        ])

In [115]:
np.sinc(x)

array([-3.89817183e-17,  3.62050725e-02, -1.93353277e-02, -4.35513208e-02,
        5.80684277e-02,  4.83383193e-02, -2.17230435e-01,  1.00000000e+00,
       -2.17230435e-01,  4.83383193e-02,  5.80684277e-02, -4.35513208e-02,
       -1.93353277e-02,  3.62050725e-02, -3.89817183e-17])